import { vars } from 'nativewind'

export const themes = {
  light: vars({
    '--background': `#ffffff`,
    '--foreground': `#0a0e1c`,
    '--card': `#ffffff`,
    '--card-foreground': `#0a0e1c`,
    '--popover': `#ffffff`,
    '--popover-foreground': `#0a0e1c`,
    '--primary': `#7c49d3`,
    '--primary-foreground': `#f6f9fc`,
    '--secondary': `#ebf0f7`,
    '--secondary-foreground': `#1b2743`,
    '--muted': `#ebf0f7`,
    '--muted-foreground': `#717a8d`,
    '--accent': `#ebf0f7`,
    '--accent-foreground': `#1b2743`,
    '--destructive': `#f54b5e`,
    '--destructive-foreground': `#f6f9fc`,
    '--border': `#d0d7e1`,
    '--input': `#d0d7e1`,
    '--ring': `#7c49d3`,
  }),
  dark: vars({
    '--background': `#0a0e1c`,
    '--foreground': `#f6f9fc`,
    '--card': `#0a0e1c`,
    '--card-foreground': `#f6f9fc`,
    '--popover': `#0a0e1c`,
    '--popover-foreground': `#f6f9fc`,
    '--primary': `#7155c2`,
    '--primary-foreground': `#f6f9fc`,
    '--secondary': `#1b2434`,
    '--secondary-foreground': `#f6f9fc`,
    '--muted': `#1b2434`,
    '--muted-foreground': `#8f95a8`,
    '--accent': `#1b2434`,
    '--accent-foreground': `#f6f9fc`,
    '--destructive': `#992f2f`,
    '--destructive-foreground': `#f6f9fc`,
    '--border': `#1b2434`,
    '--input': `#1b2434`,
    '--ring': `#7155c2`,
  }),
}
